[package]
name = "serde-example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
chrono = "0.4.38"
serde_with = "3.9.0"
