[package]
name = "websocket-example"
version = "0.1.0"
edition = "2021"

[dependencies]
tungstenite = { version = "0.23.0", features = ["native-tls"] }
futures-util = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
log = "0.4.22"
serde_json = "1.0.121"
chrono = "0.4.38"
